//firebase_options.dart


// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsaLjO2MOWfPCAjMn_0Aa1Wsr_QS36vUQ',
    appId: '1:207335654352:web:20fbaa84840b37fd696fd5',
    messagingSenderId: '207335654352',
    projectId: 'todoapp-project-d1dd0',
    authDomain: 'todoapp-project-d1dd0.firebaseapp.com',
    storageBucket: 'todoapp-project-d1dd0.firebasestorage.app',
    measurementId: 'G-HP0NZCBL2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhf_ugVYeZUYDD34O9n1yvx1CM6B-_9rs',
    appId: '1:207335654352:android:5d61af969390b39f696fd5',
    messagingSenderId: '207335654352',
    projectId: 'todoapp-project-d1dd0',
    storageBucket: 'todoapp-project-d1dd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgxhDS_aVIEsbmhwJHvQrYUobGO2XmaxY',
    appId: '1:207335654352:ios:0a1d645148018b0d696fd5',
    messagingSenderId: '207335654352',
    projectId: 'todoapp-project-d1dd0',
    storageBucket: 'todoapp-project-d1dd0.firebasestorage.app',
    iosBundleId: 'com.example.todoAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgxhDS_aVIEsbmhwJHvQrYUobGO2XmaxY',
    appId: '1:207335654352:ios:0a1d645148018b0d696fd5',
    messagingSenderId: '207335654352',
    projectId: 'todoapp-project-d1dd0',
    storageBucket: 'todoapp-project-d1dd0.firebasestorage.app',
    iosBundleId: 'com.example.todoAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsaLjO2MOWfPCAjMn_0Aa1Wsr_QS36vUQ',
    appId: '1:207335654352:web:cf27fc2702faeff0696fd5',
    messagingSenderId: '207335654352',
    projectId: 'todoapp-project-d1dd0',
    authDomain: 'todoapp-project-d1dd0.firebaseapp.com',
    storageBucket: 'todoapp-project-d1dd0.firebasestorage.app',
    measurementId: 'G-YT98Y4JWCZ',
  );
}
